version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: worldmeds-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - worldmeds_db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: worldmeds-backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: worldmeds-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  worldmeds_db_data:
